name: hnm
channels:
  - pytorch
  - anaconda
  - conda-forge
  - defaults
  - pytorch-lts
dependencies:
  - cudatoolkit=11.7
  - numpy=1.25.0
  - pillow=10.1.0
  - pip=23.2.1
  - python=3.10.12
  - pytorch=2.3.1
  - torchvision=0.18.1
  - tensorboard=2.17.0
  - matplotlib=3.8.0
  - scikit-learn=1.3.2
  - pyyaml=6.0
  - nvidia-apex=0.1
  - pandas=2.0.0
  - scikit-image=0.23.2
  - jupyterlab=3.2.8
  - opencv=4.8.0.76
  - tqdm=4.66.1